
#!/bin/sh
#PBS -l procs=1,pmem=4gb
#PBS -l walltime=400:00:00
#PBS -j oe
#PBS -m a
#PBS -V
#PBS -M begumtop@umich.edu
#PBS -A pschloss_fluxod
#PBS -q fluxod
#PBS -l qos=flux
#PBS -t 1-100

# Load Modules:
#  1) R/3.5.0
#  2)  r-biomed-libs

# -t is array parameter, the same job will be submitted the length of the input,
# each with its own unique array id ($PBS_ARRAYID)


cd $PBS_O_WORKDIR
# vector index starts at 0 so shift array by one
cd $PBS_O_WORKDIR
seed=$(($PBS_ARRAYID - 1))

make data/process/best_hp_results_L2_Logistic_Regression_$seed.csv
make data/process/best_hp_results_L1_Linear_SVM_$seed.csv
make data/process/best_hp_results_L2_Logistic_Regression_$seed.csv
make data/process/best_hp_results_RBF_SVM_$seed.csv
make data/process/best_hp_results_Decision_Tree_$seed.csv
make data/process/best_hp_results_Random_Forest_$seed.csv
make data/process/best_hp_results_XGBoost_$seed.csv

echo "Script complete"
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
qstat -f $PBS_JOBID
exit
