################################################################################
#
# plot_nmds.R
#
# Here we take in the *.nmds.axes file from the mouse stability analysis and
# plot it in R as we did in Figure 4 of Kozich et al.
#
# Dependencies:   2-D axes file generated by the nmds command in mothur
# Produces:	  results/figures/nmds_figure.png
#
################################################################################
library(tidyverse)
library(ggplot2)




axes <- read.table(file="data/baxter.braycurtis.0.03.lt.ave.nmds.axes",
                   header=T)
meta <- read.delim('data/metadata.tsv', header=T, sep='\t') %>%
  select(sample, Dx_Bin, fit_result)

data <- inner_join(meta, axes, by=c("sample"="group")) %>%
  mutate(dx = case_when(
    Dx_Bin== "Adenoma" ~ "normal",
    Dx_Bin== "Normal" ~ "normal",
    Dx_Bin== "High Risk Normal" ~ "normal",
    Dx_Bin== "adv Adenoma" ~ "cancer",
    Dx_Bin== "Cancer" ~ "cancer"
  )) %>%
  select(-sample, -Dx_Bin, -fit_result) %>%
  drop_na() %>% 
  mutate(Diagnosis=dx)


ggplot(data) +
  aes(x=axis1, y=axis2, col=Diagnosis) +
  geom_point(pch=19) +
  labs(x="NMDS Axis 1", y="NMDS Axis 2") +
  scale_color_brewer(palette="Set1", labels=c("SRN", "Normal"), name=NULL) +
  theme_classic() +
  theme(#legend.justification=c(1,0),
        #legend.position=c(1,0),
        legend.position="bottom",
        legend.title = element_blank(),
        legend.background = element_rect(linetype="solid", color="black", size=0.5),
        legend.box.margin=margin(c(0.5,0.5,0.5,0.5)),
        legend.text=element_text(size=12),
        axis.title = element_text(size=14),
        axis.text = element_text(size=12),
        panel.border = element_rect(colour = "black", fill=NA, size=1)
  ) +
  ggsave("submission/nmds_figure.png")



