---
title: ""
output:
  pdf_document:
    keep_tex: false
    includes:
      in_header: header.tex
geometry: margin=1.0in
fontsize: 11pt
---

\captionof{table}{An aspirational rubric for evaluating the rigor of ML practices.}
\small
\begin{tabular}{|l|l|l|l|}
\hline

\rowcolor{lightgray}
\textbf{Practice} & \textbf{Good} & \textbf{Better} & \textbf{Best} \\ \hline

\makecell[l]{Problem \\ definition} & \makecell[l]{Have we clearly stated \\ the ML task? \\ Do we have a priori hypotheses? \\Do we know the predictions \\ a domain expert would \\ make manually?} & \makecell[l]{Do we know the motivation \\ for solving the problem? \\ How much interpretability \\ does the problem need? } & \makecell[l]{Do we know our data? \\ Do we know the confounding \\ variables? } \\ \hline

\makecell[l]{Model \\ selection} & \makecell[l]{Do we know the \\ candidate algorithms \\ for the ML problem? \\} & \makecell[l]{Do we know our \\ computational resources \\ to fully train each model?} & \makecell[l]{How much interpretibility \\ does the problem need? \\ How much each \\ candidate algorithm \\ can provide?} \\ \hline

\makecell[l]{ML pipeline \\ preparation} & \makecell[l]{Do we have an held-out \\ test dataset?} & \makecell[l]{Have we tested our model \\ on many different \\ held-out datasets?} & \makecell[l]{Have we tuned our model \\ hyperparameters in \\ cross-validation?} \\ \hline

\makecell[l]{Hyperparameter \\ selection} & \makecell[l]{Do we know the different \\ hyperparameters each model \\ can use and why?} & \makecell[l]{Did we use historically \\ effective hyperparameters? } & \makecell[l]{Did we search the \\ full grid space and \\optimized our model? } \\ \hline

\makecell[l]{Model \\ evaluation} & \makecell[l]{Have we chosen an appropriate \\ metric to evaluate \\ predictive performance?} & \makecell[l]{Have we reported \\ the predictive performance \\ on a held-out test data?} & \makecell[l]{Have we provided an average \\ predictive performance \\ of many model runs? } \\ \hline

\makecell[l]{Model \\ interpretation} & \makecell[l]{Do we know if \\ our model is \\ interpretable?} & \makecell[l]{If the model is not \\ interpretable, do we know \\how to  explain it? \\ Have we checked for \\ the effect of confounding \\ variables?} & \makecell[l]{Have we generated new \\ hypotheses based on \\ model interpretation \\ to test model results? } \\ \hline

\end{tabular}

